<?php
$url = explode('/', $_SERVER['REQUEST_URI']);

$url1 = $url[count($url) - 1];
$url2 = $url[count($url) - 2];
//echo $url1.' - '.$url2;
if ((Zend_Auth::getInstance()->hasIdentity()) || ($url1 == 'login')) {
    $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
    $this->headTitle()->setSeparator(' - ');
    $this->headTitle('IQ - Instituto de Química ');
    echo $this->doctype();

    $zendAuth = Zend_Auth::getInstance()->getIdentity();
    $user = $_SESSION['tipo'];

    if ($zendAuth != "") {
        if ($user != 'admin') {
            echo"<style>
	      		.botao{display:none;}
	      		.linkRemove{display:none;}
	      		.linkChange{display:none;}
	      		
	      		</style>";
            if ($_POST) {
                $_POST = array();
            }
        }
    }
    ?>
    <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
        <head>



            <?php echo $this->headMeta(); ?>
            <?php echo $this->headTitle(); ?>
            <link
                href="<?php echo $this->baseUrl() . '/assets/css/site.css'; ?>"
                media="screen" rel="stylesheet" type="text/css" />

            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/mascara.js' ?>"></script>
            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/jquery-1.4.2.min.js' ?>"></script>
            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/flexigrid/flexigrid.js' ?>"></script>
            <link
                href="<?php echo $this->baseUrl() . '/assets/js/flexigrid/css/flexigrid/flexigrid.css' ?>"
                media="screen" rel="stylesheet" type="text/css" />
            <link
                href="<?php echo $this->baseUrl() . '/assets/js/superfish/css/superfish.css' ?>"
                media="screen" rel="stylesheet" type="text/css" />
            <link
                href="<?php echo $this->baseUrl() . '/assets/js/superfish/css/superfish-vertical.css' ?>"
                media="screen" rel="stylesheet" type="text/css" />
    <!--        <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/superfish/js/hoverIntent.js' ?>"></script>-->

            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/superfish/js/superfish.js' ?>"></script>

            <!--        <script type="text/javascript"
                    src="<?php echo $this->baseUrl() . '/assets/js/superfish/js/supersubs.js' ?>"></script>-->

            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/jquery.maskedinput.min.js' ?>"></script>

            <script type="text/javascript"
            src="<?php echo $this->baseUrl() . '/assets/js/jquery.maskMoney.js' ?>"></script>
            <link
                href="<?php echo $this->baseUrl() . '/assets/js/facebox/facebox.css' ?>"
                media="screen" rel="stylesheet" type="text/css" />
            <script
                src="<?php echo $this->baseUrl() . '/assets/js/facebox/facebox.js' ?>"
            type="text/javascript"></script>
            <script type="text/javascript" src="https://www.google.com/jsapi"></script>
            <?php
            $baseurl = $_SERVER['PHP_SELF'];
            $baseurl = str_replace('/index.php', '', $baseurl);
            $url = $_SERVER['REQUEST_URI'];
            $final = str_replace($baseurl, '', $url);
            $final = explode('/', $final);
            $_modules = $final[1];
            $_controller = $final[2];
            $_action = $final[3];
            $tipoDeUser = $_SESSION['tipo'];
            ?>

            <script type="text/javascript">
                $(document).ready(function() {

    <?php
    if ($tipoDeUser == 'user' && ($_modules != "procurar" &&
            $_modules != "materias" && $_modules != "relatorios" && $_modules != "login")) {
        ?>
                    $("form").submit( function () {
                        return false;
                    } );

        <?php
    }
    ?>	
            $('.crud-toggle').hide();
            $('.crud-toggle-button').click(function()
            {
                $('.crud-toggle').toggle('fast');
            }
            				
        );
            jQuery(function(){
                $('a[rel*=facebox]').facebox();
                jQuery('ul.sf-menu').superfish({
                    delay:       125,                            // one second delay on mouseout
                    animation:   {opacity:'show',height:'show'},  // fade-in and slide-down animation
                    speed:       'fast',                          // faster animation speed
                    autoArrows:  false,                           // disable generation of arrow mark-up
                    dropShadows: true                            // disable drop shadows
                });
            			
            });
        });
        function subtituirVirgula(){
                             

            $.each( $("input"), function(k, v){
                var v=$(this).val().replace(/~#044~{1}/gi,",");
                if(v!="")
                    $(this).val(v);
            });
                                                
            $.each( $("textarea"), function(k, v){
                var v=$(this).val().replace(/~#044~{1}/gi,",");
                if(v!="")
                    $(this).val(v);
            });

        }
        function doDelete(data, func)
        {
            a = window.confirm('Deseja realmente excluir este dado?\nEsta operação não poderá ser revertida\n');
            if(a)
            {
                func(data)
                //alert('Dados excluidos com sucesso');
            }
            else
            {
            }
        }
        function trim(str){
            return str.replace(/^\s+|\s+$/g,"");
        }
            	
        function getParams(data)
        {
            var re = new RegExp('\{[^}]*\}', "g");
            var m0 = re.exec(data);
            var pResult = m0[0].substring(1, m0[0].length - 1);
            var arrResult = new Array();
            arrResult = pResult.split(',');
            params    = new Array();
            for(i = 0; i < arrResult.length; i++)
            {
                var tmp = arrResult[i].split(":");
                params[trim(tmp[0].replace(':', ''))] = unescape(trim(tmp[1].replace("'", "").replace("'", "")));
            }
            return params;
            		
        }

            </script>
       
        </head>
        <body>

            <p style="text-align: center; color: #e9e9e9; font-size: 10px;">Sistema
                de Pós Graduação do Instituto de Química da UNICAMP v1.5 - Desenvolvido
                por ECCEN</p>
            <table width="100%" style="z-index: 5;">
                <tr>
                    <td colspan="2" valign="top" on>
                        <div class="sf-menu-border-l superMenu" style="z-index: 5;"></div>
                        <div class="menu-superior" style="z-index: 5;">
                            <ul id="menu" style="z-index: 5;">
                                <li><label href="#">Principal</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'dashboard', 'controller' => 'index'), null, true); ?>/">Dashboard</a></li>
                                    </ul>
                                </li>

                                <li><label href="#">Procurar</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'procurar', 'controller' => 'pessoas', 'action' => 'index'), null, true); ?>/">Pessoas</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'materias', 'controller' => 'procurar'), null, true) ?>/">Turmas</a></li>
                                    </ul>
                                </li>

                                <li><label href="#">Inserir</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'pessoas', 'controller' => 'geral', 'action' => 'index'), null, true) ?>/">Pessoas</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'materias', 'controller' => 'inserir'), null, true) ?>/">Turmas</a></li>
                                    </ul>
                                </li>

                                <li><label href="#">Estatísticas</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'estatisticas', 'controller' => 'index', 'action' => 'inscricoes'), null, true); ?>">Inscritos por semestre e ano</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'estatisticas', 'controller' => 'index', 'action' => 'alunosativos'), null, true); ?>">Alunos
            				por curso e ano</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'estatisticas', 'controller' => 'index', 'action' => 'defesas'), null, true); ?>">Defesas
            				por curso e ano</a></li>

                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'estatisticas', 'controller' => 'index', 'action' => 'bolsa'), null, true); ?>">Bolsas
            				por agência e ano</a></li>

                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'estatisticas', 'controller' => 'index', 'action' => 'orientadores'), null, true); ?>">Alunos
            				por orientador e ano</a></li>

                                    </ul>
                                </li>

                                <li><label href="#">Relatórios</label>
                                    <ul>
                                        <li><a href="#">Formulários</a>
                                            <ul>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Formularios', 'action' => 'matricula'), null, true); ?>">Comprovante
            					de Matrícula</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Formularios', 'action' => 'participacaobanca'), null, true); ?>">Participação
            					em Banca</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Formularios', 'action' => 'presenca'), null, true); ?>">Frequêcia
            					Mensal</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Formularios', 'action' => 'defesa'), null, true); ?>">Defesa</a></li>
                                            </ul>
                                        </li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'defesasocorridas'), null, true); ?>">Defesas
            				Ocorridas</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'alunocancelados'), null, true); ?>">Alunos
            				que cancelaram o curso</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'alunonotabaixa'), null, true); ?>">Alunos
            				com nota baixa</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'conclusaocurso'), null, true); ?>">Conclusão
            				curso</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'reprovadosdefesa'), null, true); ?>">Reprovados
                    				em defesa</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'examesqualificacao'), null, true); ?>">Exames
                    				Qualificação</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'bolsistas'), null, true); ?>">Bolsistas</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'inscritos'), null, true); ?>">Inscritos</a></li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'relatorios', 'controller' => 'Index', 'action' => 'alunoscurso'), null, true); ?>">Alunos
                    				em Curso</a></li>
                                    </ul>
                                </li>
                                <?php if ($user == 'admin') {
                                    ?>
                                    <li><label href="#">Pessoas</label>
                                        <ul>
                                            <li><a
                                                    href="<?php echo $this->url(array('module' => 'procurar', 'controller' => 'pessoas', 'action' => 'index'), null, true); ?>/">Procurar</a></li>
                                            <li><a
                                                    href="<?php echo $this->url(array('module' => 'pessoas', 'controller' => 'geral', 'action' => 'index'), null, true) ?>/">Inserir</a></li>
                                        </ul>
                                    </li>
                                <?php } ?>
                                <li><label href="#">Turmas</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'materias', 'controller' => 'procurar'), null, true) ?>/">Procurar</a></li>
                                            <?php if ($user == 'admin') { ?>
                                            <li><a
                                                    href="<?php echo $this->url(array('module' => 'materias', 'controller' => 'inserir'), null, true) ?>/">Inserir</a></li>
                                            <?php } ?>
                                    </ul>
                                </li>

                                <li><label href="#">Gerenciar</label>
                                    <ul>
                                        <li><a href="#">Geral</a>
                                            <ul>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'areas-de-concentracao'), null, true) ?>/">Áreas
                        					de concentração</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'cidades-da-prova'), null, true) ?>/">Cidades
                        					da prova</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'cursos'), null, true) ?>/">Cursos</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'departamentos'), null, true) ?>/">Departamentos</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'instituicoes'), null, true) ?>/">Instituições</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'linhas-de-pesquisa'), null, true) ?>/">Linhas
            					de pesquisa</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'periodos'), null, true) ?>/">Períodos</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'user'), null, true) ?>/">Usuários</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Pós-Graduação </a>
                                            <ul>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'atividades'), null, true) ?>/">Atividades</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'detalhes-do-desligado'), null, true) ?>/">Detalhes
            					de Desligamento</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'disciplinas'), null, true) ?>/">Disciplinas</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'linguas'), null, true) ?>/">Línguas</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'oferecimentos-disciplinas'), null, true) ?>/">Oferecimentos
            					de Disciplinas</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'publicacoes'), null, true) ?>/">Tipos
            					Publicações</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'tipos-projetos'), null, true) ?>/">Tipos
            					de Projetos</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'tipos-de-trancamento'), null, true) ?>/">Tipos
            					de trancamento</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'notas-maximas-doutorado'), null, true) ?>/">Notas máxima exame doutorado</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'coordenadores'), null, true) ?>/">Coordenador</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Docentes</a>
                                            <ul>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'aposentadorias'), null, true) ?>/">Aposentadoria</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'atribuicoes'), null, true) ?>/">Atribuições
            					em Banca</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'tipodocente'), null, true) ?>/">Tipo
            					de docente</a></li>
                                            </ul>
                                        </li>
                                        <li><a href="#">Bolsas</a>
                                            <ul>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'agencias'), null, true) ?>/">Agências</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'motivos-de-cancelamento'), null, true) ?>/">Motivos
            					de cancelamento</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'motivo-suspensao-bolsa'), null, true) ?>/">Motivos
            					para suspensão de bolsa</a></li>
                                                <li><a
                                                        href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'nivelbolsa'), null, true) ?>/">Nivel
            					de bolsa produtividade</a></li>
                                            </ul>
                                        </li>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'gerenciar', 'controller' => 'siga'), null, true) ?>/">Importar
                    				SIGA</a></li>
                                    </ul>
                                </li>


                                <li><label href="#">Logs de acesso</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'logs', 'controller' => 'index'), null, true) ?>">Ver
                    				logs</a></li>
                                    </ul>
                                </li>

                                <li><label href="#">Sair</label>
                                    <ul>
                                        <li><a
                                                href="<?php echo $this->url(array('module' => 'login', 'controller' => 'index', 'action' => 'logout'), null, true) ?>/">Sair
                            				do sistema</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="sf-menu-border-r superMenu"></div>
                    </td>
                </tr>
                <tr>
                    <td valign="top" width="0">
                        <img src="<?php echo $this->baseUrl() . '/assets/img/logo-iq.jpg' ?>"
                             class="superMenu" /></td>

                    <td valign="top">
                        <div style="overflow: auto;"><?php echo $this->layout()->content; ?></div>
                    </td>
                </tr>
            </table>

            <script type="text/javascript">
                $(document).ready(function()
                {
    <?php
    if (isset($this->alert)) {
        echo 'alert("' . $this->alert . '");';
    }
    ?>
    <?php
    if (isset($_REQUEST['alert'])) {
        echo 'alert("' . $_REQUEST['alert'] . '");';
    }
    ?>
        });
        $(document).ready(function(){
            $("#menu li").hover(function(){
                $(this).find('ul:first').css('display', 'block');
            }, function(){
                $(this).find('ul:first').css('display', 'none');
            });
        });
            </script>
        </body>
    </html>
    <?php
} else {
    if ($_SERVER['REQUEST_URI'] != "/iqm2010/trunk/www/login") {
        header('location: ' . $this->url(array('module' => 'login', 'controller' => 'index'), null, true));
    }
}
?>
