<div class="divPessoasMenuMestrado">
	<a id="mestrado-inscricoes" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'inscricoes' ),null,false) ?>" class="mestrado-inscricoes">Inscrições</a> |
	<a id="mestrado-exames" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'exames'),null,false) ?>" class="mestrado-exame">Exames</a> |		
	<a id="mestrado-ingresso" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'ingressos' )) ?>" class="mestrado-outros">Ingressos</a> |
	<a id="mestrado-atividades" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'atividades' )) ?>" class="mestrado-outros">Atividades</a> |
	<a id="mestrado-bolsas" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'bolsas' )) ?>" class="mestrado-outros">Bolsas</a> |
	<a id="mestrado-qualificacoes" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'qualificacoes' )) ?>" class="mestrado-outros">Dados de Qualificação</a> |
	<a id="mestrado-defesas" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'defesas' )) ?>" class="mestrado-outros">Dados de Defesa</a> |
	<a id="mestrado-disciplinas" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'disciplinas' )) ?>" class="mestrado-outros">Disciplina</a> |
	<a id="mestrado-linguas" href="<?php echo $this->url(array('module'=> 'mestrado', 'controller'=> 'linguas' )) ?>" class="mestrado-outros">Línguas</a>
</div>
<br />