<div class="divPessoasMenuMestrado">
	<a id="doutorado-inscricoes" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'inscricoes' , 'tipo'=>'5'),null,false) ?>" class="mestrado-inscricoes">Inscrições</a> |
	<a id="doutorado-exames" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'exames', 'tipo'=>'5'),null,false) ?>" class="doutorado-exame">Exames</a> |		
	<a id="doutorado-ingresso" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'ingressos' , 'tipo'=>'5')) ?>" class="doutorado-outros">Ingressos</a> |
	<a id="doutorado-atividades" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'atividades' , 'tipo'=>'5')) ?>" class="doutorado-outros">Atividades</a> |
	<a id="doutorado-bolsas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'bolsas' )) ?>" class="doutorado-outros">Bolsas</a> |
	<a id="doutorado-qualificacoes" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'qualificacoes' , 'tipo'=>'5')) ?>" class="doutorado-outros">Dados de Qualificação por área</a> |
	<a id="doutorado-qualificacoes" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'qualificacoes' , 'tipo'=>'5')) ?>" class="doutorado-outros">Dados de Qualificação Geral</a> |
	<a id="doutorado-defesas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'defesas' )) ?>" class="doutorado-outros">Dados de Defesa</a> |
	<a id="doutorado-disciplinas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'disciplinas', 'tipo'=>'5' )) ?>" class="doutorado-outros">Disciplina</a> |
	<a id="doutorado-linguas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'linguas', 'tipo'=>'5' )) ?>" class="doutorado-outros">Línguas</a>
</div>
<br />