<div class="divPessoasMenuMestrado">
	<a id="mestrado-inscricoes" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'inscricoes' , 'tipo'=>'3'),null,false) ?>" class="mestrado-inscricoes">Inscrições</a> |
<!--	<a id="mestrado-exames" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'exames', 'tipo'=>'3'),null,false) ?>" class="mestrado-exame">Exames</a> |		-->
	<a id="mestrado-exames" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'exames', 'tipo'=>'3')) ?>" class="mestrado-exame">Exames</a> |	
	<a id="mestrado-ingresso" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'ingressos' , 'tipo'=>'3')) ?>" class="mestrado-outros">Ingressos</a> |
	<a id="mestrado-atividades" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'atividades' , 'tipo'=>'3')) ?>" class="mestrado-outros">Atividades</a> |
	<a id="mestrado-bolsas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'bolsas', 'tipo'=>'3' )) ?>" class="mestrado-outros">Bolsas</a> |
	<a id="mestrado-qualificacoes" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'qualificacoes' , 'tipo'=>'3')) ?>" class="mestrado-outros">Dados de Qualificação</a> |
	<a id="mestrado-defesas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'defesas', 'tipo'=>'3'  )) ?>" class="mestrado-outros">Dados de Defesa</a> |
	<a id="mestrado-disciplinas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'disciplinas', 'tipo'=>'3' )) ?>" class="mestrado-outros">Disciplina</a> |
	<a id="mestrado-linguas" href="<?php echo $this->url(array('module'=> 'posgraduacao', 'controller'=> 'linguas', 'tipo'=>'3' )) ?>" class="mestrado-outros">Línguas</a>
</div>
<br />