<?php 
$a0 = range(0, 1000, 1);
echo $this->partial('partials/fieldset.phtml', array(
	'height' => 400,
'title' => 'Tipos de Trancamento',
	'content' => $this->partial('partials/flexigrid.phtml', 
		array(
			'isCrud'      => true,
			'doubleClick' => "carregaBox(this.className)",
            'table'       => $this->data,
		    'functionDelete' => 'deleteData',
		    'exclude'     => array('id_tipo_trancamento', 'deletado', 'soma_integralizacao'),
		    'headers'     => array('tipo_trancamento' => 'Tipo de Trancamento', 'modifica' => 'Prazo de integralização')
		)
	) . '
<div class="crud-c">
<p style="text-align:right"><a href="#" class="crud-toggle-button">Novo Tipo de Trancamento</a></p>
<form class="zend_form crud-toggle" method="post">
	<table width="100%">
	<tr><td width="20%"><label>Tipo de Trancamento:</td><td width="80%"><input type="text" name="data" id="data" style="width:100%"></label></td></tr>
	 <tr><td width="20%"><label>Modificar data de integralização:</td><td width="80%"><input type="checkbox" id="conta" name="conta" value="1"></label></td></tr> 
	<tr><td></td><td><input type="submit" class="submit"  value="Gravar" /></td></tr>
	</table>
</form>
</div>	'
));
?>
<script type="text/javascript">
function carregaBox(data)
{
	var re = new RegExp('\{[^}]*\}', "g");
    var m0 = re.exec(data);
    var pResult = m0[0].substring(1, m0[0].length - 1);
    var arrResult = new Array();
    arrResult = pResult.split(',');
    params    = new Array();
    for(i = 0; i < arrResult.length; i++)
    {
        var tmp = arrResult[i].split(":");
        params[trim(tmp[0].replace(':', ''))] = unescape(trim(tmp[1].replace("'", "").replace("'", "")));
    	    
    }   
    
   	jQuery.facebox('<div id="faceboxForm">');
//alert(params['soma_integralizacao']);
        var tabela = '\
			<form action="" class="zend_form" method="post" id="formCreate"> \
	        <input type="hidden" name="id" id="id" value="' + params['id_tipo_trancamento'] + '"> \
	        <table  style="width:100%"> \
	        <tr><td>Tipo de Trancamento:</td><td><input type="text" id="dado" name="dado" value="' + params['tipo_trancamento'] + '"  style="width:100%"></td></tr> \
	        <tr><td>Modificar data de integralização:</td><td><input type="checkbox" id="ckconta" name="ckconta" value="1" '+(params['soma_integralizacao']=="1"?'checked=\"checked\"':'')+' ></td></tr> \
	        <tr><td></td><td><input type="submit" class="submit"  value="Ok"></td></tr> \
	        </table> \
	    </form>';
	$('#faceboxForm').append(tabela);

        tabela= null;
}
function deleteData(data)
{
    p = getParams(data);
    location.href='<?php echo $this->url(array('module'=> 'gerenciar', 'controller'=> 'tipos-de-trancamento', 'action' => 'delete')); ?>/id/' + p['id_tipo_trancamento']; 
	//alert('Excluindo dado ' + );
}
</script>